apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  namespace: hello
  labels: { app: counter }
spec:
  replicas: 2
  selector: { matchLabels: { app: counter } }
  template:
    metadata: { labels: { app: counter } }
    spec:
      containers:
        - name: app
          image: yomu03/counter:1.0.0
          ports: [{ name: http, containerPort: 3000 }]
          env:
            - name: MONGO_URL
              value: "mongodb://mongo:27017/helloapp"
          readinessProbe: { httpGet: { path: /readyz, port: http }, initialDelaySeconds: 5 }
          livenessProbe:  { httpGet: { path: /healthz, port: http }, initialDelaySeconds: 10 }
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits:   { cpu: "500m", memory: "256Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: counter
  namespace: hello
spec:
  selector: { app: counter }
  ports:
    - name: http
      port: 3000
      targetPort: http
  type: ClusterIP
